services:
  db:
    image: mariadb:11.7
    container_name: db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=rootdev
      - MARIADB_DATABASE=dormsphere_db
    ports: 
      - 3306:3306
    volumes:
      - db_dormsphere_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_DB
    ports:
      - 8080:80
    depends_on:
      - db

  backend-app:
    container_name: backend-app
    build:
      context: ./fastapi-backend/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./fastapi-backend:/usr/src/app/backend
    depends_on:
      - db

  frontend-app:
    container_name: frontend-app
    build: 
      context: ./next-frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./next-frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    depends_on:
      - backend-app
  
volumes:
  db_dormsphere_volume:
    driver: local